apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mariadb
  labels:
    {{- include "ctfd.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 3306
    name: mysql
    targetPort: 3306
    protocol: TCP
  selector:
    {{- include "ctfd.selectorLabels" . | nindent 4 }}
    component: mariadb