ctfd:
  replicaCount: 1
  image:
    repository: ilwebshops.azurecr.io/ctfd
    tag: v2
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8000
  env:
    SECRET_KEY: sdjafoiheqiohfasjoiasjdifosafjlkyoisfaudyfuoxucibbxoyugfakgrehvbadsf
    UPLOAD_FOLDER: /var/uploads
    DATABASE_URL: mysql+pymysql://ctfd:ctfd@ctfd-mariadb/ctfd
    REDIS_URL: redis://ctfd-redis:6379
    WORKERS: "1"
    LOG_FOLDER: /var/log/CTFd
    ACCESS_LOG: "-"
    ERROR_LOG: "-"
    REVERSE_PROXY: "true"
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi

mariadb:
  image:
    repository: ilwebshops.azurecr.io/mariadb
    tag: 10.11
    pullPolicy: IfNotPresent
  rootPassword: ctfd
  user: ctfd
  password: ctfd
  database: ctfd
  volumeSize: 1Gi

redis:
  image:
    repository: ilwebshops.azurecr.io/redis
    tag: 4
    pullPolicy: IfNotPresent
  volumeSize: 1Gi

nginx:
  image:
    repository: ilwebshops.azurecr.io/nginx
    tag: stable
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    ports:
      http: 80
