ctfd:
  replicaCount: 1
  image:
    repository: ilwebshops.azurecr.io/ctfd
    tag: v2
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8000
  env:
    SECRET_KEY: sdjafoiheqiohfasjoiasjdifosafjlkyoisfaudyfuoxucibbxoyugfakgrehvbadsf
    UPLOAD_FOLDER: /var/uploads
    DATABASE_URL: mysql+pymysql://ctfd:ctfd@ctfd-mariadb/ctfd
    REDIS_URL: redis://ctfd-redis-master:6379
    WORKERS: "1"
    LOG_FOLDER: /var/log/CTFd
    ACCESS_LOG: "-"
    ERROR_LOG: "-"
    REVERSE_PROXY: "true"
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi

mariadb:
  image:
    repository: mariadb
    tag: 10.11
    pullPolicy: IfNotPresent
  rootPassword: ctfd
  user: ctfd
  password: ctfd
  database: ctfd
  volumeSize: 1Gi

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      path: /data
      size: 2Gi

nginx:
  enabled: true
  
  image:
    repository: nginx
    tag: stable
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    ports:
      http: 80
