apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    {{- include "ctfd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
  - port: 80
    targetPort: 80
  selector:
    {{- include "ctfd.selectorLabels" . | nindent 4 }}
    component: nginx