apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "ctfd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ctfd.service.type }}
  ports:
  - port: {{ .Values.ctfd.service.port }}
    targetPort: 8000
  selector:
    {{- include "ctfd.selectorLabels" . | nindent 4 }}
    component: ctfd